export const HTTP_SUCCESS_STATUS = 200

export const NO_AUTH_STATUS = 401

export const ERROR_CODE = {
  TOKEN_EXCEED_TIME: 'BACK_LOGIN',
  NEED_LOGIN: 'BACK_LOGIN',
  USER_NOT_FOUND: 'BACK_LOGIN',
  INTERNAL_ERROR: 'ERROR',
  CHECK_FAIL: 'BACK_LOGIN',
  VERIFY_ERROR:'BACK_LOGIN',
}
