-- 建库 若以存在AIOPS_RESOURCE模式，请删除下面CREATE SCHEMA "AIOPS_RESOURCE"命令
CREATE SCHEMA "AIOPS_RESOURCE";
set schema AIOPS_RESOURCE;

-- 应用表
CREATE TABLE "AIOPS_RESOURCE"."SYS_APPLICATION"
(
 "APPLICATION_ID" BIGINT IDENTITY(1,1) NOT NULL,
 "WORK_SPACE_ID" BIGINT NOT NULL,
 "DATA_GROUP_ID" BIGINT NOT NULL,
 "APPLICATION_NAME" VARCHAR(300) NULL,
 "APPLICATION_CODE" VARCHAR(600) NULL,
 "REMARK" VARCHAR(600) NULL,
 "ISVALID" BIT DEFAULT 1
 NOT NULL,
 "CREATE_USER" BIGINT NULL,
 "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "MODIFY_USER" BIGINT NULL,
 "MODIFY_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL
);

-- 配置表
CREATE TABLE "AIOPS_RESOURCE"."SYS_CONFIG"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "PARENT_ID" BIGINT DEFAULT 0
 NOT NULL,
 "PROPERTY_TYPE" VARCHAR(180) NOT NULL,
 "PROPERTY_KEY" VARCHAR(300) NOT NULL,
 "PROPERTY_VALUE" VARCHAR(600) NULL,
 "SORT_NUM" INT DEFAULT 0
 NOT NULL,
 "ISVALID" BIT DEFAULT 1
 NOT NULL,
 "REMARK" VARCHAR(600) NULL
);

-- 业务组表
CREATE TABLE "AIOPS_RESOURCE"."SYS_DATA_GROUP"
(
 "DATA_GROUP_ID" BIGINT IDENTITY(1,1) NOT NULL,
 "WORK_SPACE_ID" BIGINT NOT NULL,
 "PARENT_ID" BIGINT DEFAULT 0
 NOT NULL,
 "DATA_GROUP_NAME" VARCHAR(300) NULL,
 "DATA_GROUP_TOKEN" VARCHAR(300) NULL,
 "ISELEMENT" BIT NOT NULL,
 "REMARK" VARCHAR(600) NULL,
 "SORT_NUM" INT DEFAULT 0
 NOT NULL,
 "ISVALID" BIT DEFAULT 1
 NOT NULL,
 "CREATE_USER" BIGINT NULL,
 "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "MODIFY_USER" BIGINT NULL,
 "MODIFY_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL
);

-- 菜单表
CREATE TABLE "AIOPS_RESOURCE"."SYS_MENU"
(
 "MENU_ID" BIGINT IDENTITY(1000,1) NOT NULL,
 "MENU_NAME" VARCHAR(300) NULL,
 "PARENT_ID" BIGINT DEFAULT 0
 NOT NULL,
 "MODULE_TYPE" VARCHAR(90) NULL,
 "MENU_PATH" VARCHAR(300) NULL,
 "ISGROUP" BIT DEFAULT 0
  NOT NULL,
 "ISMENU" BIT DEFAULT 1
 NOT NULL,
 "ISOUTLINK" BIT DEFAULT 0
 NOT NULL,
 "ICON" VARCHAR(300) NULL,
 "SORT_NUM" INT DEFAULT 0
 NOT NULL,
 "ISDEFAULT" BIT DEFAULT 0
 NOT NULL,
 "ISVALID" BIT DEFAULT 1
 NOT NULL,
 "CREATE_USER" BIGINT NULL,
 "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "MODIFY_USER" BIGINT NULL,
 "MODIFY_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "MENU_NO" VARCHAR(180) NULL
);

-- 菜单接口、按钮
CREATE TABLE "AIOPS_RESOURCE"."SYS_MENU_RESOURCE"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "MENU_ID" BIGINT NOT NULL,
 "METHOD" VARCHAR(600) NULL,
 "PATH" VARCHAR(600) NULL,
 "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL
);


-- 角色表
CREATE TABLE "AIOPS_RESOURCE"."SYS_ROLE"
(
 "ROLE_ID" BIGINT IDENTITY(1,1) NOT NULL,
 "WORK_SPACE_ID" BIGINT DEFAULT 0
 NOT NULL,
 "ROLE_NAME" VARCHAR(300) NULL,
 "ISSUPERADMIN" BIT DEFAULT 0
 NOT NULL,
 "ISDEFAULT" BIT DEFAULT 0
 NOT NULL,
 "REMARK" VARCHAR(600) NULL,
 "ISVALID" BIT DEFAULT 1
 NOT NULL,
 "CREATE_USER" BIGINT NULL,
 "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "MODIFY_USER" BIGINT NULL,
 "MODIFY_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL
);

-- 角色菜单关系表
CREATE TABLE "AIOPS_RESOURCE"."SYS_ROLE_MENU"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "ROLE_ID" BIGINT NOT NULL,
 "MENU_ID" BIGINT NOT NULL,
 "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL
);

-- 用户表
CREATE TABLE "AIOPS_RESOURCE"."SYS_USER"
(
 "USER_ID" BIGINT IDENTITY(1,1) NOT NULL,
 "ACCOUNT" VARCHAR(300) NULL,
 "PASSWD" VARCHAR(300) NULL,
 "NICK_NAME" VARCHAR(300) NULL,
 "EMAIL" VARCHAR(300) NULL,
 "PHONE" VARCHAR(180) NULL,
 "FEISHU_USER_ID" VARCHAR(128) NULL,
 "IT_WORKBENCH_USER_ID" VARCHAR(128) NULL,
 "IDENTITY_SOURCE" VARCHAR(20) DEFAULT 'LOCAL' NOT NULL,
 "LDAP_ACCOUNT" VARCHAR(128) NULL,
 "HEAD_IMG" VARCHAR(300) NULL,
 "ISACTIVE" BIT DEFAULT 1
 NOT NULL,
 "ISLOGGEDIN" BIT DEFAULT 0
 NOT NULL,
 "LOGIN_TIME" TIMESTAMP(0) NULL,
 "PASSWD_MODIFY_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "ISVALID" BIT DEFAULT 1
 NOT NULL,
 "CREATE_USER" BIGINT NULL,
 "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "MODIFY_USER" BIGINT NULL,
 "MODIFY_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "GUIDE_STATE" VARCHAR(3000) NOT NULL DEFAULT '{}',
 "SIGN" VARCHAR(3000) NULL
);

-- 用户角色表
CREATE TABLE "AIOPS_RESOURCE"."SYS_USER_ROLE"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "USER_ID" BIGINT NOT NULL,
 "WORK_SPACE_ID" BIGINT NULL,
 "ROLE_ID" BIGINT NOT NULL,
  "SIGN" VARCHAR(3000) NULL,
 "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL
);

-- 用户工作空间表
CREATE TABLE "AIOPS_RESOURCE"."SYS_USER_WORK_SPACE"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "USER_ID" BIGINT NOT NULL,
 "WORK_SPACE_ID" BIGINT NOT NULL,
 "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL
);

-- 工作空间表
CREATE TABLE "AIOPS_RESOURCE"."SYS_WORK_SPACE"
(
 "WORK_SPACE_ID" BIGINT IDENTITY(1,1) NOT NULL,
 "WORK_SPACE_NAME" VARCHAR(300) NULL,
 "REMARK" VARCHAR(600) NULL,
 "ISDEFAULT" BIT DEFAULT 0
 NOT NULL,
 "ISVALID" BIT DEFAULT 1
 NOT NULL,
 "CREATE_USER" BIGINT NULL,
 "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "MODIFY_USER" BIGINT NULL,
 "MODIFY_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL
);

SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_APPLICATION" ON;
SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_APPLICATION" OFF;

SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_CONFIG" ON;
INSERT INTO "AIOPS_RESOURCE"."SYS_CONFIG"("ID","PARENT_ID","PROPERTY_TYPE","PROPERTY_KEY","PROPERTY_VALUE","SORT_NUM","ISVALID","REMARK") VALUES(1,0,'MODULE_TYPE','WORK_BENCH','工作台',0,1,'');
INSERT INTO "AIOPS_RESOURCE"."SYS_CONFIG"("ID","PARENT_ID","PROPERTY_TYPE","PROPERTY_KEY","PROPERTY_VALUE","SORT_NUM","ISVALID","REMARK") VALUES(2,0,'MODULE_TYPE','BUSINESS_OBSERVATION','业务观测',1,1,'');
INSERT INTO "AIOPS_RESOURCE"."SYS_CONFIG"("ID","PARENT_ID","PROPERTY_TYPE","PROPERTY_KEY","PROPERTY_VALUE","SORT_NUM","ISVALID","REMARK") VALUES(3,0,'MODULE_TYPE','ALARM_MANAGEMENT','告警管理',2,1,'');
INSERT INTO "AIOPS_RESOURCE"."SYS_CONFIG"("ID","PARENT_ID","PROPERTY_TYPE","PROPERTY_KEY","PROPERTY_VALUE","SORT_NUM","ISVALID","REMARK") VALUES(4,0,'MODULE_TYPE','ENVIRONMENT_CONFIGURATION','环境配置',3,1,'');
INSERT INTO "AIOPS_RESOURCE"."SYS_CONFIG"("ID","PARENT_ID","PROPERTY_TYPE","PROPERTY_KEY","PROPERTY_VALUE","SORT_NUM","ISVALID","REMARK") VALUES(5,0,'MODULE_TYPE','RESOURCE_CONTROL','权限管理',4,1,'');
INSERT INTO "AIOPS_RESOURCE"."SYS_CONFIG"("ID","PARENT_ID","PROPERTY_TYPE","PROPERTY_KEY","PROPERTY_VALUE","SORT_NUM","ISVALID","REMARK") VALUES(6,0,'USER_DATA','DEFAULT_PWD','star@1q2w',0,1,'');
INSERT INTO "AIOPS_RESOURCE"."SYS_CONFIG"("ID","PARENT_ID","PROPERTY_TYPE","PROPERTY_KEY","PROPERTY_VALUE","SORT_NUM","ISVALID","REMARK") VALUES(7,0,'DEPLOY_MODULE','observe-log','日志',0,1,'100');
INSERT INTO "AIOPS_RESOURCE"."SYS_CONFIG"("ID","PARENT_ID","PROPERTY_TYPE","PROPERTY_KEY","PROPERTY_VALUE","SORT_NUM","ISVALID","REMARK") VALUES(8,0,'DEPLOY_MODULE','observe-alarm','告警',0,1,'300');
INSERT INTO "AIOPS_RESOURCE"."SYS_CONFIG"("ID","PARENT_ID","PROPERTY_TYPE","PROPERTY_KEY","PROPERTY_VALUE","SORT_NUM","ISVALID","REMARK") VALUES(9,0,'DEPLOY_MODULE','observe-trace','链路',0,1,'200');
INSERT INTO "AIOPS_RESOURCE"."SYS_CONFIG"("ID","PARENT_ID","PROPERTY_TYPE","PROPERTY_KEY","PROPERTY_VALUE","SORT_NUM","ISVALID","REMARK") VALUES(10,0,'DEPLOY_MODULE','observe-metric','指标',0,1,'400');
INSERT INTO "AIOPS_RESOURCE"."SYS_CONFIG"("ID","PARENT_ID","PROPERTY_TYPE","PROPERTY_KEY","PROPERTY_VALUE","SORT_NUM","ISVALID","REMARK") VALUES(11,0,'DEPLOY_MODULE','observe-config','配置',0,1,'500');
INSERT INTO "AIOPS_RESOURCE"."SYS_CONFIG"("ID","PARENT_ID","PROPERTY_TYPE","PROPERTY_KEY","PROPERTY_VALUE","SORT_NUM","ISVALID","REMARK") VALUES(12,0,'DEPLOY_MODULE','ai-productivity','AI人效自动化',0,1,'600');
SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_CONFIG" OFF;

SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_DATA_GROUP" ON;
INSERT INTO "AIOPS_RESOURCE"."SYS_DATA_GROUP"("DATA_GROUP_ID","WORK_SPACE_ID","PARENT_ID","DATA_GROUP_NAME","DATA_GROUP_TOKEN","ISELEMENT","REMARK","SORT_NUM","ISVALID","CREATE_USER","CREATE_TIME","MODIFY_USER","MODIFY_TIME") VALUES(1,1,0,'内置业务组',null,0,null,0,1,0,TO_DATE('2023-12-20 14:42:11','YYYY-MM-DD HH24:MI:SS.FF'),0,TO_DATE('2023-12-20 14:42:11','YYYY-MM-DD HH24:MI:SS.FF'));
INSERT INTO "AIOPS_RESOURCE"."SYS_DATA_GROUP"("DATA_GROUP_ID","WORK_SPACE_ID","PARENT_ID","DATA_GROUP_NAME","DATA_GROUP_TOKEN","ISELEMENT","REMARK","SORT_NUM","ISVALID","CREATE_USER","CREATE_TIME","MODIFY_USER","MODIFY_TIME") VALUES(2,1,1,'内置数据单元','tok_294c7bd237c34500b25c862c833fd236',1,null,0,1,0,TO_DATE('2023-12-20 14:43:54','YYYY-MM-DD HH24:MI:SS.FF'),0,TO_DATE('2023-12-20 14:43:54','YYYY-MM-DD HH24:MI:SS.FF'));
SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_DATA_GROUP" OFF;

SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_MENU" ON;
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU"("MENU_ID","MENU_NAME","PARENT_ID","MODULE_TYPE","MENU_PATH","ISGROUP","ISMENU","ISOUTLINK","ICON","SORT_NUM","ISDEFAULT","ISVALID","CREATE_USER","MODIFY_USER","MENU_NO") VALUES(1,'工作台',0,'WORK_BENCH','/control',0,1,0,'',0,1,1,1,1,'gongzuotai');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU"("MENU_ID","MENU_NAME","PARENT_ID","MODULE_TYPE","MENU_PATH","ISGROUP","ISMENU","ISOUTLINK","ICON","SORT_NUM","ISDEFAULT","ISVALID","CREATE_USER","MODIFY_USER","MENU_NO") VALUES(2,'空间',0,'RESOURCE_CONTROL','/usermanage/space',0,1,0,'icon-kongjian',0,0,1,1,1,'kongjian');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU"("MENU_ID","MENU_NAME","PARENT_ID","MODULE_TYPE","MENU_PATH","ISGROUP","ISMENU","ISOUTLINK","ICON","SORT_NUM","ISDEFAULT","ISVALID","CREATE_USER","MODIFY_USER","MENU_NO") VALUES(3,'业务组管理',2,'RESOURCE_CONTROL','/usermanage/space/business',0,1,0,'icon-yewuzuguanli',0,0,1,1,1,'yewuzuguanli');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU"("MENU_ID","MENU_NAME","PARENT_ID","MODULE_TYPE","MENU_PATH","ISGROUP","ISMENU","ISOUTLINK","ICON","SORT_NUM","ISDEFAULT","ISVALID","CREATE_USER","MODIFY_USER","MENU_NO") VALUES(4,'用户管理',2,'RESOURCE_CONTROL','/usermanage/space/user',0,1,0,'icon-yonghuguanli',0,0,1,1,1,'yonghuguanli');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU"("MENU_ID","MENU_NAME","PARENT_ID","MODULE_TYPE","MENU_PATH","ISGROUP","ISMENU","ISOUTLINK","ICON","SORT_NUM","ISDEFAULT","ISVALID","CREATE_USER","MODIFY_USER","MENU_NO") VALUES(5,'角色管理',2,'RESOURCE_CONTROL','/usermanage/space/role',0,1,0,'icon-jiaoseguanli',0,0,1,1,1,'jueseguanli');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU"("MENU_ID","MENU_NAME","PARENT_ID","MODULE_TYPE","MENU_PATH","ISGROUP","ISMENU","ISOUTLINK","ICON","SORT_NUM","ISDEFAULT","ISVALID","CREATE_USER","MODIFY_USER","MENU_NO") VALUES(6,'用户池',0,'RESOURCE_CONTROL','/usermanage/pool',0,1,0,'icon-yonghuchi',0,0,1,1,1,'yonghuchi');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU"("MENU_ID","MENU_NAME","PARENT_ID","MODULE_TYPE","MENU_PATH","ISGROUP","ISMENU","ISOUTLINK","ICON","SORT_NUM","ISDEFAULT","ISVALID","CREATE_USER","MODIFY_USER","MENU_NO") VALUES(7,'菜单',0,'RESOURCE_CONTROL','/usermanage/menu',0,1,0,'icon-caidan',0,0,1,1,1,'caidan');
SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_MENU" OFF;

SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_ROLE" ON;
INSERT INTO "AIOPS_RESOURCE"."SYS_ROLE"("ROLE_ID","WORK_SPACE_ID","ROLE_NAME","ISSUPERADMIN","ISDEFAULT","REMARK","ISVALID","CREATE_USER","CREATE_TIME","MODIFY_USER","MODIFY_TIME") VALUES(1,0,'超管',1,0,null,1,0,TO_DATE('2023-12-18 10:22:02','YYYY-MM-DD HH24:MI:SS.FF'),0,TO_DATE('2023-12-18 10:22:09','YYYY-MM-DD HH24:MI:SS.FF'));
INSERT INTO "AIOPS_RESOURCE"."SYS_ROLE"("ROLE_ID","WORK_SPACE_ID","ROLE_NAME","ISSUPERADMIN","ISDEFAULT","REMARK","ISVALID","CREATE_USER","CREATE_TIME","MODIFY_USER","MODIFY_TIME") VALUES(2,0,'空间管理员',0,1,null,1,0,TO_DATE('2023-12-18 10:22:45','YYYY-MM-DD HH24:MI:SS.FF'),0,TO_DATE('2023-12-18 10:22:45','YYYY-MM-DD HH24:MI:SS.FF'));
SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_ROLE" OFF;

DELETE FROM "AIOPS_RESOURCE"."SYS_ROLE_MENU" WHERE "ROLE_ID" = 2;
SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_ROLE_MENU" ON;
INSERT INTO "AIOPS_RESOURCE"."SYS_ROLE_MENU"("ROLE_ID","MENU_ID","CREATE_TIME") SELECT 2,"MENU_ID",NOW() FROM "AIOPS_RESOURCE"."SYS_MENU" WHERE "MENU_NO" NOT IN ('yonghuchi','caidan');
SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_ROLE_MENU" OFF;

SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_USER" ON;
INSERT INTO "AIOPS_RESOURCE"."SYS_USER"("USER_ID","ACCOUNT","PASSWD","NICK_NAME","EMAIL","PHONE","HEAD_IMG","ISACTIVE","ISLOGGEDIN","LOGIN_TIME","PASSWD_MODIFY_TIME","ISVALID","CREATE_USER","CREATE_TIME","MODIFY_USER","MODIFY_TIME") VALUES(1,'admin','6c3a2908b4ea6d6b2e42a39b8359ee8a','超管',null,null,null,1,0,null,TO_DATE('2024-03-04 10:30:12','YYYY-MM-DD HH24:MI:SS.FF'),1,0,TO_DATE('2023-12-18 10:25:40','YYYY-MM-DD HH24:MI:SS.FF'),0,TO_DATE('2023-12-18 10:25:40','YYYY-MM-DD HH24:MI:SS.FF'));
INSERT INTO "AIOPS_RESOURCE"."SYS_USER"("USER_ID","ACCOUNT","PASSWD","NICK_NAME","EMAIL","PHONE","HEAD_IMG","ISACTIVE","ISLOGGEDIN","LOGIN_TIME","PASSWD_MODIFY_TIME","ISVALID","CREATE_USER","CREATE_TIME","MODIFY_USER","MODIFY_TIME") VALUES(2,'space','6c3a2908b4ea6d6b2e42a39b8359ee8a','空间管理员',null,null,null,1,0,null,TO_DATE('2024-03-04 10:30:12','YYYY-MM-DD HH24:MI:SS.FF'),1,0,TO_DATE('2023-12-18 10:25:40','YYYY-MM-DD HH24:MI:SS.FF'),0,TO_DATE('2023-12-18 10:25:40','YYYY-MM-DD HH24:MI:SS.FF'));
SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_USER" OFF;

SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_USER_ROLE" ON;
INSERT INTO "AIOPS_RESOURCE"."SYS_USER_ROLE"("ID","USER_ID","WORK_SPACE_ID","ROLE_ID","CREATE_TIME") VALUES(1,1,0,1,TO_DATE('2023-12-18 10:30:16','YYYY-MM-DD HH24:MI:SS.FF'));
INSERT INTO "AIOPS_RESOURCE"."SYS_USER_ROLE"("ID","USER_ID","WORK_SPACE_ID","ROLE_ID","CREATE_TIME") VALUES(2,2,1,2,TO_DATE('2023-12-18 10:30:16','YYYY-MM-DD HH24:MI:SS.FF'));
SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_USER_ROLE" OFF;

SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_USER_WORK_SPACE" ON;
INSERT INTO "AIOPS_RESOURCE"."SYS_USER_WORK_SPACE"("ID","USER_ID","WORK_SPACE_ID","CREATE_TIME") VALUES(1,2,1,TO_DATE('2023-12-18 10:29:05','YYYY-MM-DD HH24:MI:SS.FF'));
SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_USER_WORK_SPACE" OFF;

SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_WORK_SPACE" ON;
INSERT INTO "AIOPS_RESOURCE"."SYS_WORK_SPACE"("WORK_SPACE_ID","WORK_SPACE_NAME","REMARK","ISDEFAULT","ISVALID","CREATE_USER","CREATE_TIME","MODIFY_USER","MODIFY_TIME") VALUES(1,'内置空间',null,1,1,0,TO_DATE('2023-12-18 10:28:05','YYYY-MM-DD HH24:MI:SS.FF'),0,TO_DATE('2023-12-18 10:28:05','YYYY-MM-DD HH24:MI:SS.FF'));
SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_WORK_SPACE" OFF;


SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ON;
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'POST', '/auth/updatePassword');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'POST', '/auth/updateUser');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'GET', '/auth/userBaseInfo');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'GET', '/auth/menu');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'GET', '/auth/workspace');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'GET', '/auth/meta');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'GET', '/auth/validateIntegrality');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'POST', '/auth/deleteShortcutMenu/*');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'GET', '/auth/shortcutMenu');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'POST', '/auth/saveShortcutMenu');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'POST', '/alarm/analysis/level');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'POST', '/alarm/statistics/task');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'POST', '/alarm/statistics/level');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'POST', '/alarm/alarm/overview');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'POST', '/graphql/listServicesNew');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'POST', '/graphql/getErrorPm');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'POST', '/auth/guideState');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'POST', '/graphql/readMetricsValues');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'POST', '/log-platform/log/getApplicationErrorLogCount');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'GET', '/log-platform/application/list');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (1, 'GET', '/log-platform/analysis/getErrorLogDistribution');

INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (2, 'GET', '/auth/menu');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (2, 'GET', '/auth/workspace');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (2, 'GET', '/auth/meta');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (2, 'POST', '/auth/sys/workSpace/list');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (2, 'POST', '/auth/sys/workSpace/update');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (2, 'POST', '/auth/sys/workSpace/insert');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (2, 'POST', '/auth/sys/workSpace/list');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (2, 'POST', '/auth/sys/dataGroup/bizTree');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (2, 'POST', '/auth/sys/workSpace/delete');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (2, 'POST', '/auth/sys/workSpace/user/insertUser');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (2, 'POST', '/auth/sys/user/getDefaultPwd');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (2, 'POST', '/auth/sys/workSpace/listTotalDrown');

INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (3, 'POST', '/auth/sys/dataGroup/dataGroupTree');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (3, 'POST', '/auth/sys/dataGroup/dataGroupTree');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (3, 'POST', '/auth/sys/dataGroup/moveDataGroup');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (3, 'POST', '/auth/sys/application/delete');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (3, 'POST', '/auth/sys/application/update');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (3, 'POST', '/auth/sys/application/insert');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (3, 'POST', '/auth/sys/dataGroup/update');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (3, 'POST', '/auth/sys/dataGroup/insert');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (3, 'POST', '/auth/sys/dataGroup/delete');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (3, 'POST', '/auth/sys/dataGroup/update');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (3, 'POST', '/auth/sys/application/page');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (3, 'POST', '/auth/sys/dataGroup/insert');

INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (4, 'POST', '/auth/sys/workSpace/user/save');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (4, 'GET', '/auth/sys/role/listSpaceTotal');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (4, 'GET', '/auth/sys/workSpace/user/getDetail');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (4, 'POST', '/auth/sys/workSpace/user/batchRemove');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (4, 'POST', '/auth/sys/workSpace/user/save');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (4, 'GET', '/auth/sys/role/detail');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (4, 'GET', '/auth/sys/workSpace/user/listUserDrown');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (4, 'POST', '/auth/sys/workSpace/user/page');

INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (5, 'POST', '/auth/sys/role/page');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (5, 'GET', '/auth/sys/role/listTemplate');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (5, 'GET', '/auth/sys/role/getAuthMenuTree');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (5, 'POST', '/auth/sys/role/delete');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (5, 'POST', '/auth/sys/role/delete');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (5, 'POST', '/auth/sys/role/update');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (5, 'GET', '/auth/sys/role/detail');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (5, 'POST', '/auth/sys/role/insert');

INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (6, 'POST', '/auth/sys/user/page');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (6, 'GET', '/auth/sys/user/getDefaultPwd');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (6, 'POST', '/auth/sys/user/delete');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (6, 'POST', '/auth/sys/user/resetPassword');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (6, 'POST', '/auth/sys/user/update');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (6, 'POST', '/auth/sys/user/changeActive');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (6, 'POST', '/auth/sys/user/insert');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (6, 'GET', '/auth/sys/workSpace/listTotalDrown');

INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (7, 'GET', '/auth/sys/menu/getModuleSubTree');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (7, 'POST', '/auth/sys/menu/delete');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (7, 'POST', '/auth/sys/menu/update');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (7, 'GET', '/auth/sys/menu/detail');
INSERT INTO "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ("MENU_ID", "METHOD", "PATH") VALUES (7, 'POST', '/auth/sys/menu/insert');
SET IDENTITY_INSERT "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" OFF;

ALTER TABLE "AIOPS_RESOURCE"."SYS_APPLICATION" ADD CONSTRAINT  PRIMARY KEY("APPLICATION_ID") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_CONFIG" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_DATA_GROUP" ADD CONSTRAINT  PRIMARY KEY("DATA_GROUP_ID") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_MENU" ADD CONSTRAINT  PRIMARY KEY("MENU_ID") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_ROLE" ADD CONSTRAINT  PRIMARY KEY("ROLE_ID") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_ROLE_MENU" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_USER" ADD CONSTRAINT  PRIMARY KEY("USER_ID") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_USER_ROLE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_USER_WORK_SPACE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_WORK_SPACE" ADD CONSTRAINT  PRIMARY KEY("WORK_SPACE_ID") ;

CREATE INDEX "SYS_APPLICATION_DATA_GROUP_ID"
ON "AIOPS_RESOURCE"."SYS_APPLICATION"("DATA_GROUP_ID");

CREATE INDEX "SYS_APPLICATION_WORK_SPACE_ID"
ON "AIOPS_RESOURCE"."SYS_APPLICATION"("WORK_SPACE_ID");

CREATE INDEX "SYS_DATA_GROUP_PARENT_ID"
ON "AIOPS_RESOURCE"."SYS_DATA_GROUP"("PARENT_ID");

CREATE INDEX "SYS_DATA_GROUP_WORK_SPACE_ID"
ON "AIOPS_RESOURCE"."SYS_DATA_GROUP"("WORK_SPACE_ID");

CREATE INDEX "SYS_MENU_PARENT_ID"
ON "AIOPS_RESOURCE"."SYS_MENU"("PARENT_ID");

CREATE INDEX "SYS_MENU_RESOURCE_MENU_ID"
ON "AIOPS_RESOURCE"."SYS_MENU_RESOURCE"("MENU_ID");

CREATE INDEX "SYS_ROLE_WORK_SPACE_ID"
ON "AIOPS_RESOURCE"."SYS_ROLE"("WORK_SPACE_ID");

ALTER TABLE "AIOPS_RESOURCE"."SYS_MENU" ADD CONSTRAINT "SYS_MENU_MENU_NO" UNIQUE("MENU_NO") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_ROLE_MENU" ADD CONSTRAINT "SYS_ROLE_MENU_ROLE_MENU_ID" UNIQUE("ROLE_ID","MENU_ID") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_USER" ADD CONSTRAINT "SYS_USER_ACCOUNT" UNIQUE("ACCOUNT") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_USER_ROLE" ADD CONSTRAINT "SYS_USER_ROLE_USER_SPACE_ROLE_ID" UNIQUE("USER_ID","WORK_SPACE_ID","ROLE_ID") ;

ALTER TABLE "AIOPS_RESOURCE"."SYS_USER_WORK_SPACE" ADD CONSTRAINT "SYS_USER_WORK_GROUP_USER_WORK_SPACE_ID" UNIQUE("USER_ID","WORK_SPACE_ID") ;

COMMENT ON TABLE "AIOPS_RESOURCE"."SYS_APPLICATION" IS '应用';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_APPLICATION"."APPLICATION_ID" IS '应用id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_APPLICATION"."WORK_SPACE_ID" IS '工作空间id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_APPLICATION"."DATA_GROUP_ID" IS '数据单元id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_APPLICATION"."APPLICATION_NAME" IS '应用名称';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_APPLICATION"."APPLICATION_CODE" IS '应用code';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_APPLICATION"."REMARK" IS '备注';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_APPLICATION"."ISVALID" IS '是否有效';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_APPLICATION"."CREATE_USER" IS '创建者';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_APPLICATION"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_APPLICATION"."MODIFY_USER" IS '更新者';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_APPLICATION"."MODIFY_TIME" IS '更新时间';

COMMENT ON TABLE "AIOPS_RESOURCE"."SYS_CONFIG" IS '公用配置/字典表';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_CONFIG"."ID" IS '主键id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_CONFIG"."PARENT_ID" IS '父id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_CONFIG"."PROPERTY_TYPE" IS '类型 菜单按钮标识/子平台编码等';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_CONFIG"."PROPERTY_KEY" IS '属性名';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_CONFIG"."PROPERTY_VALUE" IS '属性值';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_CONFIG"."SORT_NUM" IS '平级内序号';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_CONFIG"."ISVALID" IS '是否有效';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_CONFIG"."REMARK" IS '备注';

COMMENT ON TABLE "AIOPS_RESOURCE"."SYS_DATA_GROUP" IS '业务组';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_DATA_GROUP"."DATA_GROUP_ID" IS 'id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_DATA_GROUP"."WORK_SPACE_ID" IS '工作空间id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_DATA_GROUP"."PARENT_ID" IS '父id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_DATA_GROUP"."DATA_GROUP_NAME" IS '名称';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_DATA_GROUP"."DATA_GROUP_TOKEN" IS 'token';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_DATA_GROUP"."ISELEMENT" IS '是否数据单元';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_DATA_GROUP"."REMARK" IS '备注';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_DATA_GROUP"."SORT_NUM" IS '序号';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_DATA_GROUP"."ISVALID" IS '是否有效';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_DATA_GROUP"."CREATE_USER" IS '创建者';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_DATA_GROUP"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_DATA_GROUP"."MODIFY_USER" IS '更新者';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_DATA_GROUP"."MODIFY_TIME" IS '更新时间';

COMMENT ON TABLE "AIOPS_RESOURCE"."SYS_MENU" IS '菜单表';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."MENU_ID" IS '菜单id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."MENU_NAME" IS '菜单名称';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."PARENT_ID" IS '父id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."MODULE_TYPE" IS '服务模块，来自sys_config表';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."MENU_PATH" IS '菜单地址';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."ISGROUP" IS '是否菜单分组';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."ISMENU" IS '是否菜单';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."ISOUTLINK" IS '是否外链';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."ICON" IS '图标';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."SORT_NUM" IS '序号';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."ISDEFAULT" IS '是否默认，默认菜单每个用户都有';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."ISVALID" IS '是否有效';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."CREATE_USER" IS '创建者';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."MODIFY_USER" IS '更新者';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."MODIFY_TIME" IS '更新时间';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_MENU"."MENU_NO" IS '菜单编码';

COMMENT ON TABLE "AIOPS_RESOURCE"."SYS_MENU_RESOURCE" IS '菜单接口资源';

COMMENT ON TABLE "AIOPS_RESOURCE"."SYS_ROLE" IS '角色表';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE"."ROLE_ID" IS '角色id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE"."WORK_SPACE_ID" IS '工作空间id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE"."ROLE_NAME" IS '角色名称';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE"."ISSUPERADMIN" IS '是否超管';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE"."ISDEFAULT" IS '是否默认，内置角色中超管为N';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE"."REMARK" IS '备注';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE"."ISVALID" IS '是否有效';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE"."CREATE_USER" IS '创建者';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE"."MODIFY_USER" IS '更新者';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE"."MODIFY_TIME" IS '更新时间';

COMMENT ON TABLE "AIOPS_RESOURCE"."SYS_ROLE_MENU" IS '角色菜单关系';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE_MENU"."ID" IS '主键';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE_MENU"."ROLE_ID" IS '角色id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE_MENU"."MENU_ID" IS '菜单id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_ROLE_MENU"."CREATE_TIME" IS '创建时间';

COMMENT ON TABLE "AIOPS_RESOURCE"."SYS_USER" IS '用户表';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."USER_ID" IS '用户id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."ACCOUNT" IS '账号';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."PASSWD" IS '密码';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."NICK_NAME" IS '昵称';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."EMAIL" IS '邮箱地址';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."PHONE" IS '联系方式';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."HEAD_IMG" IS '头像';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."ISACTIVE" IS '是否启用';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."ISLOGGEDIN" IS '是否登录过，没有则是未激活';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."LOGIN_TIME" IS '用户登录时间';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."PASSWD_MODIFY_TIME" IS '密码变更时间';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."ISVALID" IS '是否有效';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."CREATE_USER" IS '创建者';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."MODIFY_USER" IS '更新者';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."MODIFY_TIME" IS '更新时间';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."GUIDE_STATE" IS '新手指引状态';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER"."SIGN" IS '利川完整性校验加密字段';

COMMENT ON TABLE "AIOPS_RESOURCE"."SYS_USER_ROLE" IS '用户角色关系';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER_ROLE"."ID" IS '主键';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER_ROLE"."USER_ID" IS '用户id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER_ROLE"."WORK_SPACE_ID" IS '工作空间id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER_ROLE"."ROLE_ID" IS '角色id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER_ROLE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER_ROLE"."SIGN" IS '利川完整性校验加密字段';

COMMENT ON TABLE "AIOPS_RESOURCE"."SYS_USER_WORK_SPACE" IS '用户工作空间关系';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER_WORK_SPACE"."ID" IS '主键';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER_WORK_SPACE"."USER_ID" IS '用户id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER_WORK_SPACE"."WORK_SPACE_ID" IS '工作空间id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_USER_WORK_SPACE"."CREATE_TIME" IS '创建时间';

COMMENT ON TABLE "AIOPS_RESOURCE"."SYS_WORK_SPACE" IS '工作空间';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_WORK_SPACE"."WORK_SPACE_ID" IS '工作空间id';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_WORK_SPACE"."WORK_SPACE_NAME" IS '工作空间名称';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_WORK_SPACE"."REMARK" IS '备注';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_WORK_SPACE"."ISDEFAULT" IS '是否默认，内置空间不可删除';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_WORK_SPACE"."ISVALID" IS '是否有效';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_WORK_SPACE"."CREATE_USER" IS '创建者';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_WORK_SPACE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_WORK_SPACE"."MODIFY_USER" IS '更新者';

COMMENT ON COLUMN "AIOPS_RESOURCE"."SYS_WORK_SPACE"."MODIFY_TIME" IS '更新时间';

CREATE TABLE "AIOPS_RESOURCE"."SYS_SHORTCUT_MENU"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"MENU_ID" BIGINT NOT NULL,
"MENU_PATH" VARCHAR(300) NULL,
"ACCOUNT" VARCHAR(100) NOT NULL,
"WORKSPACE_ID" BIGINT NOT NULL,
"CREATE_TIME" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
"MODIFY_TIME" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE IF NOT EXISTS "AIOPS_RESOURCE"."SYS_DEPLOY_META_INFO"(
  "ID" BIGINT IDENTITY(1, 1) NOT NULL,
  "MODULE_NAME" VARCHAR(100) NOT NULL,
  "MODULE_URL" VARCHAR(100)  NOT NULL,
  "CREATE_TIME" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MODIFY_TIME" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR);

