services:
  krakend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpo-api-gateway
    restart: unless-stopped
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
